hisw:
  name: hisw-boot
  version: 1.0.0

captcha:
  enable: true
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  numberLength: 1
  charLength: 4

server:
  port: 9672
  servlet:
    context-path: /hisw
  undertow:
    max-http-post-size: -1
    buffer-size: 512
    direct-buffers: true
    threads:
      io: 8
      worker: 256

logging:
  level:
    com.hisw: @logging.level@
  config: classpath:logback.xml

user:
  password:
    maxRetryCount: 5
    lockTime: 10

spring:
  application:
    name: ${hisw.name}
  messages:
    basename: i18n/messages
  profiles:
    active: @profiles.active@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false

pagehelper:
  supportMethodsArguments: true
  params: count=countSql

mybatis-flex:
  type-aliases-package: com.hisw.**.domain
  mapper-locations: com.hisw.**.mapper
  configuration:
    auto_mapping_behavior: FULL
    auto_mapping_unknown_column_behavior: NONE
    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cacheEnabled: true
  global-config:
    key-config:
      key-type: Generator
      value: snowFlakeId
    normal-value-of-logic-delete: 0
    deleted-value-of-logic-delete: 1
    logic-delete-column: del_flag
    tenant-column: tenant_id
    version-column: version


mybatis-encryptor:
  enable: false
  algorithm: BASE64
  encode: BASE64
  password:
  publicKey:
  privateKey:

api-decrypt:
  enabled: true
  headerFlag: encrypt-key
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJnNwrj4hi/y3CCJu868ghCG5dUj8wZK++RNlTLcXoMmdZWEQ/u02RgD5LyLAXGjLOjbMtC+/J9qofpSGTKSx/MCAwEAAQ==
  privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAqhHyZfSsYourNxaY7Nt+PrgrxkiA50efORdI5U5lsW79MmFnusUA355oaSXcLhu5xxB38SMSyP2KvuKNPuH3owIDAQABAkAfoiLyL+Z4lf4Myxk6xUDgLaWGximj20CUf+5BKKnlrK+Ed8gAkM0HqoTt2UZwA5E2MzS4EI2gjfQhz5X28uqxAiEA3wNFxfrCZlSZHb0gn2zDpWowcSxQAgiCstxGUoOqlW8CIQDDOerGKH5OmCJ4Z21v+F25WaHYPxCFMvwxpcw99EcvDQIgIdhDTIqD2jfYjPTY8Jj3EDGPbH2HHuffvflECt3Ek60CIQCFRlCkHpi7hthhYhovyloRYsM+IS9h/0BzlEAuO0ktMQIgSPT3aFAgJYwKpqRYKlLDVcflZFCKY7u3UP8iWi1Qw0Y=

xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*

sa-token:
  token-name: Authorization
  timeout: 7200
  active-timeout: 1800
  is-share: false
  is-log: true
  jwt-secret-key: f6f31a5f2136758f86b67cde583cb125

security:
  excludes:
    - /profile/**
    - /error
    - /login
    - /captchaImage
    - /captcha/get
    - /captcha/check
    - /genKeyPair

websocket:
  enabled: true
  path: /resource/websocket
  allowedOrigins: '*'
