hisw:
  profile: E:/a_file

mybatis-flex:
  audit_enable: true
  sql_print: true
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hisw-boot-flex?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      maximum-pool-size: 20
      minimum-idle: 10
      connectionTimeout: 30000
      validationTimeout: 5000
      idleTimeout: 600000
      maxLifetime: 1800000
      keepaliveTime: 30000

  redis:
    host: localhost
    port: 6379
    database: 0
    auth:
    timeout: 10s
    ssl: false

redisson:
  keyPrefix: hisw
  threads: 4
  nettyThreads: 8
  singleServerConfig:
    clientName: ${hisw.name}
    connectionMinimumIdleSize: 8
    connectionPoolSize: 32
    idleConnectionTimeout: 10000
    timeout: 3000
    subscriptionConnectionPoolSize: 50
